require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstrumentTypesController do

  # This should return the minimal set of attributes required to create a valid
  # InstrumentType. As you add validations to InstrumentType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all instrument_types as @instrument_types" do
      instrument_type = InstrumentType.create! valid_attributes
      get :index
      assigns(:instrument_types).should eq([instrument_type])
    end
  end

  describe "GET show" do
    it "assigns the requested instrument_type as @instrument_type" do
      instrument_type = InstrumentType.create! valid_attributes
      get :show, :id => instrument_type.id.to_s
      assigns(:instrument_type).should eq(instrument_type)
    end
  end

  describe "GET new" do
    it "assigns a new instrument_type as @instrument_type" do
      get :new
      assigns(:instrument_type).should be_a_new(InstrumentType)
    end
  end

  describe "GET edit" do
    it "assigns the requested instrument_type as @instrument_type" do
      instrument_type = InstrumentType.create! valid_attributes
      get :edit, :id => instrument_type.id.to_s
      assigns(:instrument_type).should eq(instrument_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstrumentType" do
        expect {
          post :create, :instrument_type => valid_attributes
        }.to change(InstrumentType, :count).by(1)
      end

      it "assigns a newly created instrument_type as @instrument_type" do
        post :create, :instrument_type => valid_attributes
        assigns(:instrument_type).should be_a(InstrumentType)
        assigns(:instrument_type).should be_persisted
      end

      it "redirects to the created instrument_type" do
        post :create, :instrument_type => valid_attributes
        response.should redirect_to(InstrumentType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instrument_type as @instrument_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstrumentType.any_instance.stub(:save).and_return(false)
        post :create, :instrument_type => {}
        assigns(:instrument_type).should be_a_new(InstrumentType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstrumentType.any_instance.stub(:save).and_return(false)
        post :create, :instrument_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instrument_type" do
        instrument_type = InstrumentType.create! valid_attributes
        # Assuming there are no other instrument_types in the database, this
        # specifies that the InstrumentType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstrumentType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => instrument_type.id, :instrument_type => {'these' => 'params'}
      end

      it "assigns the requested instrument_type as @instrument_type" do
        instrument_type = InstrumentType.create! valid_attributes
        put :update, :id => instrument_type.id, :instrument_type => valid_attributes
        assigns(:instrument_type).should eq(instrument_type)
      end

      it "redirects to the instrument_type" do
        instrument_type = InstrumentType.create! valid_attributes
        put :update, :id => instrument_type.id, :instrument_type => valid_attributes
        response.should redirect_to(instrument_type)
      end
    end

    describe "with invalid params" do
      it "assigns the instrument_type as @instrument_type" do
        instrument_type = InstrumentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstrumentType.any_instance.stub(:save).and_return(false)
        put :update, :id => instrument_type.id.to_s, :instrument_type => {}
        assigns(:instrument_type).should eq(instrument_type)
      end

      it "re-renders the 'edit' template" do
        instrument_type = InstrumentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstrumentType.any_instance.stub(:save).and_return(false)
        put :update, :id => instrument_type.id.to_s, :instrument_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instrument_type" do
      instrument_type = InstrumentType.create! valid_attributes
      expect {
        delete :destroy, :id => instrument_type.id.to_s
      }.to change(InstrumentType, :count).by(-1)
    end

    it "redirects to the instrument_types list" do
      instrument_type = InstrumentType.create! valid_attributes
      delete :destroy, :id => instrument_type.id.to_s
      response.should redirect_to(instrument_types_url)
    end
  end

end
